// BIP39 Portuguese wordlist (2048 words) for secure recovery
// Entropy: 6 words = 6 × 11 bits = 66 bits of security

const wordList = [
  'abacate', 'abaixo', 'abalar', 'abanar', 'abandono', 'abater', 'abdome', 'abelha',
  'aberto', 'abismo', 'abjeto', 'abolir', 'abordar', 'abrasar', 'abrupto', 'absinto',
  'absoluto', 'absorver', 'abstrato', 'absurdo', 'abundar', 'abusar', 'acabado', 'academia',
  'acalmar', 'acanhar', 'acaso', 'aceitar', 'acender', 'acervo', 'acessar', 'achado',
  'acidez', 'acima', 'acionado', 'acirrar', 'aclamar', 'aclive', 'acolher', 'acomodar',
  'acordar', 'acossar', 'acreditar', 'acudir', 'adaptar', 'adega', 'adentro', 'adepto',
  'adequar', 'aderir', 'adesivo', 'adeus', 'adiante', 'adicionar', 'adiem', 'admirar',
  'adoecer', 'adorar', 'adornar', 'adquirir', 'adubo', 'adulto', 'advento', 'advogado',
  'afagar', 'afastar', 'aferir', 'afeto', 'afiado', 'afinal', 'afinar', 'afinco',
  'afirmar', 'afivelar', 'aflito', 'afluir', 'afogar', 'afoito', 'afrontar', 'afunilar',
  'agachar', 'agarrar', 'agasalho', 'agenciar', 'agenda', 'agitar', 'aglomerar', 'agonizar',
  'agradar', 'agravar', 'agredir', 'agreste', 'aguardar', 'agudo', 'ainda', 'aipo',
  'ajudar', 'ajustar', 'alameda', 'alarme', 'alastrar', 'alavanca', 'albergue', 'alcance',
  'alegar', 'alegrar', 'aleitar', 'alergia', 'alertar', 'alface', 'alfandega', 'alfazema',
  'alfinete', 'alforriar', 'algarismo', 'algema', 'algodao', 'alguem', 'alheio', 'aliar',
  'alibi', 'alicerce', 'alienar', 'alinhar', 'aliviar', 'almofada', 'alogeno', 'alojado',
  'alongar', 'alpino', 'alquimia', 'alterar', 'altivo', 'altura', 'alucinar', 'alugar',
  'aluminio', 'aluno', 'alusivo', 'alvejar', 'alvorada', 'amaciar', 'amadurecer', 'amador',
  'amainar', 'amalgama', 'amanha', 'amansar', 'amante', 'amarelo', 'amargor', 'amassar',
  'ambiente', 'ambiguo', 'ambito', 'ameixa', 'amenizar', 'ametista', 'amido', 'amigo',
  'amistoso', 'amizade', 'amnesia', 'amolador', 'amolecer', 'amontoar', 'amostra', 'amparar',
  'ampliar', 'ampola', 'amuado', 'analfabeto', 'analogia', 'analisar', 'anatomia', 'ancora',
  'andaime', 'andar', 'anedota', 'anel', 'anemona', 'anexar', 'anfibio', 'angariar',
  'angelical', 'angulo', 'animado', 'animar', 'aniversario', 'anjo', 'anoitecer', 'anomalia',
  'anonimo', 'anotar', 'ansioso', 'antecipar', 'antena', 'anterior', 'antigo', 'antiquado',
  'antitese', 'antonimo', 'anual', 'anular', 'anunciar', 'anzol', 'apagador', 'apagar',
  'apaixonar', 'apalpar', 'apanhar', 'aparador', 'aparato', 'aparecer', 'aparelho', 'apartar',
  'apelar', 'apenas', 'apendice', 'apequeno', 'apertar', 'apetite', 'apice', 'apiedar',
  'apitar', 'aplacar', 'aplaudir', 'aplicar', 'apoiar', 'apogeu', 'apontar', 'aposento',
  'apostar', 'apoteose', 'aprender', 'aprovar', 'aproveitar', 'aproximar', 'aptidao', 'apurar',
  'aquarela', 'aquario', 'aquecer', 'aquietar', 'aquilo', 'aquisicao', 'arado', 'aramado',
  'aranha', 'arara', 'arbitrar', 'arbusto', 'arcaico', 'arcar', 'arco', 'arder',
  'ardor', 'arduamente', 'area', 'areia', 'arenoso', 'argila', 'argumentar', 'arguto',
  'arido', 'arista', 'armadilha', 'armazenar', 'arminho', 'aroma', 'arqueado', 'arquibancada',
  'arquivar', 'arraial', 'arrancar', 'arranhar', 'arranjar', 'arrebatar', 'arrecadar', 'arredar',
  'arredondar', 'arrefecer', 'arregacar', 'arrematar', 'arremessar', 'arrendar', 'arrepiar', 'arriscar',
  'arrogar', 'arrojar', 'arrombar', 'arrotar', 'arruinar', 'arrumar', 'arsenal', 'arterial',
  'artesao', 'articulado', 'artificio', 'arvoredo', 'ascender', 'ascese', 'asfalto', 'asfixia',
  'asilo', 'aspirar', 'assaltar', 'assanhar', 'assar', 'assassino', 'assedio', 'assegurar',
  'assentar', 'assessor', 'assimilar', 'assinalar', 'assinar', 'assistir', 'assoalho', 'assolar',
  'assombrar', 'assumir', 'assunto', 'assustar', 'astral', 'astro', 'astuto', 'atacar',
  'atalho', 'ataque', 'atar', 'atazanar', 'atear', 'ateliê', 'atentar', 'aterrar',
  'atestar', 'atinar', 'atingir', 'atirar', 'atitude', 'ativar', 'atleta', 'atmosfera',
  'ato', 'atomico', 'atonito', 'atracao', 'atraente', 'atrair', 'atraso', 'atravessar',
  'atrelar', 'atrever', 'atribuir', 'atrito', 'atropelar', 'atual', 'atuar', 'aturar',
  'audacia', 'audio', 'auditor', 'auge', 'augurar', 'aula', 'aumentar', 'aurora',
  'ausente', 'austero', 'autentico', 'auto', 'automatico', 'autonomia', 'autopsia', 'autor',
  'autorizar', 'auxiliar', 'avacalhar', 'avancar', 'avarento', 'ave', 'aveia', 'avelã',
  'avenida', 'aventura', 'averiguar', 'avesso', 'aviador', 'avião', 'avisar', 'aviso',
  'avistar', 'avocar', 'azarar', 'azar', 'azedado', 'azeite', 'azeitona', 'azul',
  'azulejo', 'babel', 'babosa', 'bacalhau', 'bacharel', 'bacia', 'bacteria', 'bagagem',
  'bagunca', 'baia', 'bailar', 'bairro', 'baixar', 'bajular', 'balanca', 'baleia',
  'ballet', 'balsa', 'baluarte', 'bambu', 'banana', 'bancada', 'banco', 'banda',
  'bandeira', 'banhar', 'banir', 'banquete', 'barato', 'barba', 'barbear', 'barca',
  'barco', 'barganha', 'bario', 'barnabe', 'barraca', 'barreira', 'barriga', 'barro',
  'basalto', 'base', 'basico', 'bastante', 'bastao', 'batalha', 'batata', 'batedor',
  'bateria', 'batismo', 'baunilha', 'bauru', 'bazar', 'beato', 'bebado', 'bebedor',
  'bebida', 'beco', 'beija', 'beijar', 'beijo', 'beira', 'beirado', 'beleza',
  'belo', 'beltrano', 'bemdito', 'bendizer', 'beneficiar', 'bengala', 'benigno', 'bento',
  'berco', 'berlinda', 'bermuda', 'berna', 'berrar', 'besouro', 'besteira', 'beta',
  'betume', 'bexiga', 'bibelô', 'bicama', 'bicarbonato', 'bicho', 'bicicleta', 'bicudo',
  'bienal', 'bifocal', 'bigode', 'bijuteria', 'bilhao', 'bilhete', 'bimestre', 'bimotor',
  'binario', 'bingo', 'binoculo', 'biodiesel', 'biografia', 'biologia', 'biombo', 'biometria',
  'biopsia', 'biosfera', 'biotipo', 'biruta', 'bisavo', 'biscoito', 'bispo', 'bissexto',
  'bizarro', 'blasfemia', 'blazer', 'blindar', 'blitz', 'blocar', 'blog', 'bloquear',
  'blusa', 'boate', 'bobagem', 'bobina', 'bobo', 'boca', 'bocado', 'bochecha',
  'bochechar', 'boda', 'bodega', 'boiada', 'boiar', 'boicote', 'bola', 'bolada',
  'boleia', 'boletim', 'bolha', 'bolo', 'bolsa', 'bom', 'bomba', 'bombeiro',
  'bondade', 'bondoso', 'boneco', 'bonito', 'bonus', 'boquete', 'borda', 'borboleta',
  'bordar', 'bordel', 'bordoada', 'boreal', 'borla', 'borracha', 'bosque', 'bossa',
  'bota', 'botanica', 'botao', 'boteco', 'botequim', 'boxe', 'braco', 'bradar',
  'branco', 'brasa', 'brasil', 'bravo', 'brecha', 'brega', 'brejo', 'breu',
  'breve', 'briga', 'brilhar', 'brincar', 'brinde', 'brisa', 'brita', 'broa',
  'broca', 'broche', 'bronzear', 'broto', 'bruma', 'brusco', 'brutal', 'bruxo',
  'bucha', 'budismo', 'bufar', 'bufe', 'bugre', 'bujao', 'bula', 'bulbo',
  'bule', 'bulicio', 'bunda', 'buraco', 'burguesia', 'burlar', 'burocracia', 'burro',
  'buscar', 'bussola', 'busto', 'buzina', 'cabana', 'cabeca', 'cabelo', 'cabide',
  'cabine', 'cabo', 'cabra', 'cabrito', 'cacau', 'cacetada', 'cachaca', 'cachecol',
  'cachimbo', 'cachorra', 'cachoeira', 'cacique', 'caco', 'cacto', 'cadastrar', 'cadaver',
  'cadeia', 'cadeira', 'cadela', 'caderno', 'cadete', 'caducar', 'cafe', 'cafona',
  'caiaque', 'caibro', 'caixa', 'cajado', 'caju', 'calabresa', 'calamidade', 'calango',
  'calcada', 'calcar', 'calcinha', 'calculo', 'calda', 'caldeira', 'caleidoscopio', 'calendário',
  'calibrar', 'calice', 'calma', 'calor', 'calota', 'calvo', 'cama', 'camada',
  'camafeu', 'camaleao', 'camarada', 'camarao', 'camarote', 'cambio', 'camelo', 'camera',
  'caminhada', 'caminhao', 'camisa', 'campainha', 'campanha', 'campear', 'campeao', 'campestre',
  'campismo', 'campo', 'camuflagem', 'canal', 'canario', 'canasta', 'canavar', 'cancelar',
  'cancer', 'candelabro', 'candidato', 'candomble', 'caneca', 'canela', 'caneta', 'canguru',
  'canhao', 'canino', 'canivete', 'canja', 'cano', 'canoa', 'cansaco', 'cansar',
  'cantar', 'canteiro', 'cantil', 'cantina', 'canto', 'cantor', 'canudo', 'capa',
  'capacete', 'capacidade', 'capataz', 'capaz', 'capela', 'capim', 'capital', 'capitao',
  'capivara', 'capoeira', 'capota', 'capricho', 'capsula', 'captar', 'captura', 'capuz',
  'caqui', 'cara', 'caracol', 'caramba', 'caramelo', 'caranguejo', 'carater', 'caravana',
  'carbono', 'carcaca', 'carcere', 'cardapio', 'cardeal', 'careta', 'carga', 'caridade',
  'carinhoso', 'carisma', 'carmim', 'carnaval', 'carne', 'carneiro', 'caro', 'carona',
  'carpa', 'carpete', 'carpinteiro', 'carranca', 'carregar', 'carreira', 'carrinho', 'carro',
  'carrossel', 'carta', 'cartao', 'cartaz', 'carteira', 'cartola', 'cartucho', 'carvalho',
  'casa', 'casaco', 'casal', 'casamento', 'casar', 'cascalho', 'cascata', 'casco',
  'caseiro', 'casino', 'caso', 'caspa', 'casquinha', 'cassete', 'cassia', 'castanha',
  'castelo', 'casticar', 'castigo', 'castor', 'casual', 'casulo', 'catapora', 'catar',
  'catarse', 'catastrofe', 'catedral', 'categoria', 'catequese', 'cateter', 'cativar', 'catolico',
  'causa', 'causar', 'cautela', 'cavadeira', 'cavala', 'cavalaria', 'cavalgada', 'cavalheiro',
  'cavalo', 'cavar', 'caveira', 'caverna', 'cebola', 'cedilha', 'cedo', 'cedro',
  'cegar', 'cego', 'ceia', 'ceifar', 'celebrar', 'celeiro', 'celeste', 'celibato',
  'celulose', 'cemiterio', 'cena', 'cenario', 'censor', 'centavo', 'centenario', 'centro',
  'centuriao', 'ceptico', 'ceramica', 'cerca', 'cercado', 'cereal', 'cerebral', 'cereja',
  'cerimonia', 'cerrar', 'certame', 'certeza', 'cerveja', 'cessar', 'cesta', 'cetim',
  'cevar', 'chacal', 'chacara', 'chacoalhar', 'chacota', 'chaleira', 'chama', 'chamada',
  'chamar', 'chamativo', 'champanhe', 'chance', 'chantagem', 'chapada', 'chapeu', 'charco',
  'charme', 'charuto', 'chassi', 'chato', 'chave', 'chaveiro', 'checar', 'chefe',
  'chegar', 'cheio', 'cheiro', 'cheirar', 'cheque', 'chiar', 'chicote', 'chifre',
  'chileno', 'chilique', 'chimpanze', 'chines', 'chip', 'chique', 'chiqueiro', 'chispa',
  'chita', 'chocalho', 'chocar', 'chocolate', 'choque', 'chorar', 'chorume', 'chover',
  'chuchu', 'chulapa', 'chumaco', 'chumbo', 'chupeta', 'chutar', 'chuva', 'chuveiro',
  'cicatriz', 'ciclo', 'cidadao', 'cidade', 'cifra', 'cigano', 'cigarra', 'cigarro',
  'cilindro', 'cima', 'cimento', 'cinco', 'cinegrafista', 'cinema', 'cingir', 'cinico',
  'cinismo', 'cinto', 'cintura', 'cinza', 'cinzel', 'ciranda', 'circo', 'circuito',
  'circular', 'cirurgia', 'cisco', 'cisma', 'cisne', 'cisterna', 'citacao', 'citadino',
  'citar', 'citrico', 'ciume', 'civico', 'civil', 'civilizacao', 'clamar', 'clandestino',
  'clara', 'clareira', 'clareza', 'clarinete', 'claro', 'classe', 'classico', 'clausula',
  'clausura', 'clave', 'clavicular', 'clemencia', 'clero', 'clicar', 'cliente', 'clima',
  'clinica', 'clipe', 'cloaca', 'clone', 'cloro', 'clube', 'coador', 'coagir',
  'coalhar', 'coalizao', 'coar', 'cobaia', 'cobalt', 'cobertor', 'cobica', 'cobra',
  'cobrar', 'cocada', 'cocar', 'cocegas', 'cochicho', 'cochilo', 'coco', 'coelho',
  'coentro', 'coerencia', 'cofre', 'cogitar', 'cogumelo', 'coice', 'coincidencia', 'coisa',
  'colar', 'colchao', 'colecao', 'colega', 'colegio', 'coleira', 'colera', 'coleta',
  'colete', 'colheita', 'colher', 'colidir', 'colina', 'colirio', 'colmeia', 'colmo',
  'colo', 'colocar', 'colombiano', 'colonizar', 'colono', 'coloquio', 'colorir', 'colossal',
  'coluna', 'combate', 'combinar', 'combustao', 'comecar', 'comedia', 'comer', 'cometa',
  'cometer', 'comicio', 'comida', 'comigo', 'comissao', 'comite', 'comitiva', 'como',
  'comoda', 'comoção', 'comover', 'compacto', 'compaixao', 'comparar', 'compasso', 'compelir',
  'compensar', 'competir', 'compilar', 'complicar', 'compor', 'comportar', 'compra', 'comprar',
  'comprido', 'comum', 'comunicar', 'comunismo', 'concatenar', 'conceber', 'conceder', 'conceito',
  'concentrar', 'concerto', 'concha', 'conciliar', 'concluir', 'concordar', 'concreto', 'concurso',
  'conde', 'condenar', 'condensar', 'condição', 'condor', 'conduta', 'conduzir', 'conectar',
  'conexao', 'confeccionar', 'conferir', 'confessar', 'confete', 'confiar', 'configurar', 'confinar',
  'confirmar', 'conflito', 'conformar', 'confortar', 'confraternizar', 'confrontar', 'confundir', 'congelar',
  'congresso', 'conhecer', 'conjugar', 'conjunto', 'conotar', 'conquistar', 'consagrar', 'consciencia',
  'conseguir', 'conselho', 'consentir', 'conservar', 'considerar', 'consignar', 'consistir', 'consolar',
  'consolidar', 'consorte', 'conspirar', 'constante', 'constar', 'constatar', 'constrangimento', 'construir',
  'consul', 'consultar', 'consumir', 'conta', 'contagiar', 'contaminar', 'contar', 'contemplar',
  'contempo', 'contender', 'conteudo', 'contexto', 'contigo', 'contingente', 'continuar', 'contornar',
  'contra', 'contradizer', 'contrair', 'contrastar', 'contratar', 'contribuir', 'controlar', 'contumaz',
  'contundir', 'convenio', 'conversar', 'converter', 'convexo', 'convidar', 'convir', 'conviver',
  'convocar', 'cooperar', 'coordenar', 'copa', 'copiar', 'copo', 'coquetel', 'cor',
  'coracao', 'coragem', 'coral', 'corar', 'corcunda', 'corda', 'cordeiro', 'coreto',
  'coringa', 'corneta', 'coro', 'coroa', 'coronal', 'corpete', 'corpo', 'correr',
  'corretor', 'corrida', 'corrigir', 'corroer', 'corromper', 'cortar', 'cortejo', 'cortesia',
  'cortica', 'cortina', 'coruja', 'corveta', 'corvo', 'coser', 'cosmetico', 'cosmo',
  'costa', 'costelar', 'costume', 'costura', 'cota', 'cotacao', 'cotonete', 'cotovia',
  'coube', 'couro', 'couve', 'cova', 'covarde', 'covil', 'coxa', 'coxear',
  'cozinha', 'craco', 'craneo', 'craque', 'crasso', 'cratera', 'cravar', 'cravo',
  'creche', 'credito', 'credo', 'credor', 'creme', 'crendice', 'crepusculo', 'crescer',
  'crespo', 'criacao', 'criador', 'crianca', 'criar', 'criativo', 'criatura', 'crilo',
  'crime', 'crina', 'crioulo', 'crise', 'crisma', 'cristal', 'critério', 'critica',
  'crocante', 'cromo', 'cronica', 'crosta', 'crucial', 'crucifixo', 'cruel', 'crustaceo',
  'cruz', 'cruzar', 'cubo', 'cubrir', 'cuco', 'cueca', 'cuidado', 'cujo',
  'culatra', 'culinaria', 'culpa', 'culpar', 'culto', 'cultivar', 'cultura', 'cumplice',
  'cumprir', 'cumulo', 'cunhado', 'cupido', 'cupom', 'cupula', 'cura', 'curativo',
  'curiosidade', 'curral', 'curriculo', 'cursar', 'cursor', 'curta', 'curto', 'curva',
  'custar', 'custo', 'cutelo', 'dado', 'dama', 'danca', 'dancar', 'danificar',
  'dano', 'daqui', 'dardo', 'data', 'debalde', 'debater', 'debil', 'debitar',
  'deboche', 'decada', 'decair', 'decente', 'decepcao', 'decidir', 'decifrar', 'decimo',
  'decisao', 'declarar', 'declinar', 'decolar', 'decorar', 'decreto', 'dedicar', 'dedo',
  'deduzir', 'defeito', 'defender', 'defesa', 'deficit', 'definir', 'defumar', 'degrau',
  'degustar', 'deitar', 'deixar', 'delegar', 'deletar', 'deleite', 'delicado', 'delicia',
  'delinear', 'delito', 'delta', 'demais', 'demasiado', 'demencia', 'demitir', 'democracia',
  'demolir', 'demonio', 'demora', 'demorar', 'denegar', 'denegrir', 'dengue', 'denodo',
  'denominar', 'denotar', 'densidade', 'denso', 'dente', 'dentro', 'denunciar', 'deparar',
  'dependurar', 'depilar', 'deplorar', 'depor', 'depositar', 'depois', 'depravar', 'depreciar',
  'depressao', 'deprimir', 'deputado', 'deriva', 'derradeiro', 'derramar', 'derrotar', 'derrubar',
  'desabar', 'desabito', 'desabrochar', 'desacato', 'desafiar', 'desafogar', 'desagradar', 'desajuste',
  'desamparar', 'desandar', 'desanimar', 'desaprovar', 'desarmar', 'desastre', 'desatar', 'desatento',
  'desativar', 'descalco', 'descansar', 'descartar', 'descascar', 'descender', 'descer', 'descobrir',
  'descontar', 'descrever', 'descuido', 'desculpa', 'desde', 'desdenhar', 'desdobrar', 'desejar',
  'desembaracar', 'desembarcar', 'desempenhar', 'desenhar', 'desenrolar', 'desenvolver', 'deserto', 'desesperado',
  'desfalque', 'desfecho', 'desfiar', 'desfilar', 'desgaste', 'desgostar', 'desgraca', 'desidratar',
  'designar', 'desigual', 'desilusao', 'desistir', 'desleal', 'desligar', 'deslizar', 'deslumbrar',
  'desmaiar', 'desmanchar', 'desmatar', 'desmentir', 'desmerecer', 'desmontar', 'desnecessario', 'desnudar',
  'desobedecer', 'desocupar', 'desolado', 'desordem', 'despachar', 'despedida', 'despejo', 'desperdicar',
  'despertar', 'despesa', 'despir', 'despojar', 'despontar', 'desporto', 'desprezar', 'depois',
  'destacar', 'destampar', 'destaque', 'destempo', 'desterrar', 'destinar', 'destino', 'destituir',
  'destravar', 'destreza', 'destrocar', 'destruir', 'desunir', 'desvairar', 'desviar', 'detalhar',
  'deter', 'deteriorar', 'determinar', 'detestar', 'detido', 'detonar', 'detrimento', 'deturpar',
  'deus', 'devagar', 'devaneio', 'devassar', 'dever', 'devido', 'devir', 'devorar',
  'devotar', 'dezembro', 'dia', 'diabo', 'diadema', 'dialeto', 'dialogo', 'diamante',
  'diante', 'diario', 'dica', 'dieta', 'diferir', 'dificil', 'difuso', 'digerir',
  'digital', 'digitar', 'digno', 'dilema', 'diligente', 'diluir', 'diluvio', 'dimensao',
  'diminuir', 'dinamica', 'dinastia', 'dinheiro', 'dinossauro', 'diocese', 'diploma', 'dique',
  'direito', 'direcao', 'dirigir', 'discernir', 'disciplina', 'discordar', 'discorrer', 'discoteca',
  'discurso', 'discutir', 'disfarcar', 'disforme', 'disparar', 'dispensar', 'dispersar', 'dispor',
  'disputar', 'dissabor', 'dissecar', 'disseminar', 'dissipar', 'dissolucao', 'dissuadir', 'distancia',
  'distinto', 'distorcer', 'distrair', 'distribuir', 'distrito', 'ditado', 'ditador', 'ditar',
  'diversao', 'diverso', 'divertir', 'dividir', 'divino', 'divisa', 'divisao', 'divorcio',
  'divulgar', 'dizer', 'dobrar', 'doceiro', 'docil', 'doctor', 'documento', 'doenca',
  'doente', 'doer', 'dogma', 'dolar', 'dolencia', 'doloroso', 'dom', 'domar',
  'domestico', 'domicilio', 'dominar', 'domingo', 'dominio', 'dona', 'donativo', 'dono',
  'donzela', 'dopar', 'dopado', 'doravante', 'dormir', 'dorsal', 'dorso', 'dosagem',
  'dose', 'dossie', 'dotado', 'dotar', 'dote', 'dourado', 'doutrina', 'doutor',
  'draga', 'dragao', 'drama', 'drastico', 'dreno', 'droga', 'dual', 'dubio',
  'ducado', 'duelo', 'duende', 'dueto', 'dulce', 'dunga', 'dupla', 'duplo',
  'duque', 'duracao', 'durante', 'durar', 'dureza', 'duro', 'duvidoso', 'duzento',
  'ebano', 'ecoar', 'ecologia', 'economia', 'edema', 'edificar', 'edital', 'editar',
  'editor', 'educacao', 'educar', 'efeito', 'efetuar', 'eficaz', 'eixo', 'elaborar',
  'elastico', 'elegancia', 'eleger', 'elemento', 'eletronica', 'elevador', 'elevar', 'eliminar',
  'elite', 'elogiar', 'elucidar', 'emanar', 'emancipar', 'embaracar', 'embarcar', 'embate',
  'emblema', 'embolsar', 'embora', 'embraiagem', 'embrulho', 'embutir', 'emendar', 'emergir',
  'emigrar', 'eminente', 'emissao', 'emitir', 'emocao', 'empacar', 'empada', 'empalhar',
  'empanar', 'empate', 'empenhar', 'empilhar', 'empobrecer', 'empolar', 'emporio', 'empresa',
  'emprego', 'emprestar', 'empunhar', 'empurrar', 'emudecer', 'emular', 'enamorar', 'encadear',
  'encaixar', 'encalhar', 'encanar', 'encantar', 'encapar', 'encarar', 'encargo', 'encarnar',
  'encerar', 'encerrar', 'encharcar', 'encher', 'enciclopedia', 'encimar', 'encolher', 'encomendar',
  'encontrar', 'encorajar', 'encosta', 'encostar', 'encrencar', 'encurtar', 'enderecar', 'endereço',
  'endoidar', 'endossar', 'endurecer', 'energia', 'enfado', 'enfase', 'enfatizar', 'enfeitar',
  'enfermo', 'enferrujar', 'enfiar', 'enfileirar', 'enfim', 'enforcar', 'enfraquecer', 'enfrentar',
  'enfurecer', 'engajar', 'engambelar', 'enganar', 'engano', 'engarrafar', 'engasgar', 'engavetar',
  'engendrar', 'engenharia', 'englobar', 'engolir', 'engordar', 'engracado', 'engraxar', 'engrenagem',
  'engrossar', 'enguia', 'enigma', 'enjoar', 'enlacar', 'enlameado', 'enlouquecer', 'enlutar',
  'enorme', 'enquadrar', 'enquanto', 'enraizar', 'enredo', 'enriquecer', 'enrolar', 'enrugar',
  'ensaiar', 'ensaio', 'enseada', 'ensejo', 'ensinar', 'ensolarado', 'entalar', 'entanto',
  'entao', 'enteado', 'entender', 'enterrar', 'entidade', 'entoar', 'entrada', 'entrar',
  'entregar', 'entrelinha', 'entretanto', 'entreter', 'entrevista', 'entulho', 'entupir', 'entusiasmo',
  'enumerar', 'enunciar', 'enveredar', 'envergar', 'envelope', 'envergonhar', 'enviar', 'enviesar',
  'envio', 'envolver', 'enxada', 'enxaguar', 'enxame', 'enxaqueca', 'enxergar', 'enxerto',
  'enxofre', 'enxotar', 'enxoval', 'enxugar', 'enzima', 'epico', 'epidemia', 'epilogo',
  'episodio', 'epitafio', 'epoca', 'equacao', 'equador', 'equilibrar', 'equipar', 'equipe',
  'equivocar', 'era', 'erguer', 'erigir', 'erma', 'erodir', 'erosao', 'erotismo',
  'erradicar', 'errar', 'erro', 'erupção', 'esbater', 'esbelto', 'esbocar', 'esboco',
  'esbravejar', 'esburcar', 'escada', 'escala', 'escaldao', 'escaldar', 'escapar', 'escarpa',
  'escasso', 'escavar', 'escola', 'escolha', 'escolher', 'escolta', 'esconder', 'escore',
  'escorrer', 'escova', 'escovar', 'escravo', 'escrever', 'escritor', 'escritura', 'escudo',
  'esculpir', 'escuridao', 'escuro', 'escutar', 'esfera', 'esforcar', 'esfregao', 'esfriar',
  'esgoto', 'esgotar', 'esgrima', 'esguio', 'esmeralda', 'esmero', 'esmola', 'espaço',
  'espada', 'espalhado', 'espancar', 'espanto', 'espargo', 'especialidade', 'especie', 'espectador',
  'espelho', 'espera', 'esperar', 'espertar', 'espesso', 'espetaculo', 'espetar', 'espeto',
  'espiado', 'espiar', 'espiga', 'espinhaco', 'espinho', 'espirar', 'espirito', 'espirrar',
  'esplendor', 'espolio', 'esponja', 'espontaneo', 'esporte', 'esposa', 'espremer', 'espuma',
  'esquadrao', 'esquecer', 'esqueleto', 'esquema', 'esquerda', 'esqui', 'esquilo', 'esquina',
  'esquivar', 'estabilizar', 'estaca', 'estacionar', 'estagio', 'estagnar', 'estalar', 'estampa',
  'estancar', 'estante', 'estar', 'estatal', 'estatica', 'estatua', 'estatura', 'estatuto',
  'este', 'esteio', 'esteira', 'estender', 'esterno', 'estetica', 'esticar', 'estilete',
  'estilo', 'estima', 'estimular', 'estio', 'estirar', 'estocar', 'estofado', 'estojo',
  'estomago', 'estoque', 'estourar', 'estrada', 'estragar', 'estranhar', 'estrear', 'estreito',
  'estrela', 'estresse', 'estribo', 'estridente', 'estrondo', 'estrutura', 'estuario', 'estudante',
  'estudar', 'estudo', 'estufa', 'etapa', 'eterno', 'etica', 'etiqueta', 'eu',
  'europeu', 'evacuar', 'evadir', 'evaporar', 'evento', 'eventual', 'evidenciar', 'evitar',
  'evolucao', 'evocar', 'exagerar', 'exalar', 'exaltar', 'exame', 'examinar', 'exato',
  'exaurir', 'exceção', 'exceder', 'excelente', 'excentrico', 'excerto', 'excessivo', 'excitar',
  'exclamar', 'excluir', 'excursao', 'executar', 'exemplar', 'exercer', 'exercicio', 'exibir',
  'exilar', 'existir', 'exito', 'exonerar', 'exorcismo', 'exotico', 'expandir', 'expectativa',
  'expedir', 'expelir', 'experiencia', 'experimento', 'expirar', 'explicar', 'explodir', 'explorar',
  'expor', 'exportar', 'expressar', 'expulsar', 'extenuar', 'exterior', 'exterminar', 'externo',
  'extinguir', 'extorquir', 'extrair', 'extremo', 'extrovertido', 'exuberante', 'fabricar', 'fabula',
  'faca', 'facada', 'facade', 'faceta', 'facial', 'facil', 'facilitar', 'faco',
  'fada', 'fadiga', 'fado', 'fagulha', 'faixa', 'falar', 'falcao', 'falecido',
  'falecer', 'falencia', 'falha', 'falhar', 'falido', 'falo', 'falsa', 'falsear',
  'falso', 'falta', 'faltar', 'fama', 'familia', 'faminto', 'famoso', 'fanatico',
  'fanfarra', 'fantasia', 'fantasma', 'fardo', 'farejar', 'farofa', 'farol', 'farpa',
  'farra', 'farrapo', 'farsa', 'fartar', 'farto', 'fartura', 'fascinar', 'fase',
  'fatal', 'fatiar', 'fato', 'fator', 'fatura', 'fauna', 'favor', 'favorito',
  'fazenda', 'fazer', 'febre', 'fechar', 'fecha', 'fecho', 'fecula', 'federa',
  'federa', 'federacao', 'feder', 'feijoada', 'feijao', 'feio', 'feira', 'feito',
  'feitico', 'feitor', 'feixe', 'fel', 'felicidade', 'felino', 'feliz', 'feltro',
  'femea', 'feminino', 'femur', 'fenda', 'fender', 'fenomenal', 'fenomeno', 'fera',
  'feriado', 'ferida', 'ferir', 'fermentar', 'fernanda', 'fero', 'ferocidade', 'feroz',
  'ferradura', 'ferramenta', 'ferrao', 'ferrar', 'ferreiro', 'ferro', 'fertil', 'ferver',
  'fervor', 'festa', 'festejar', 'festivo', 'feto', 'fevereiro', 'fibra', 'ficar',
  'fichario', 'fidalgo', 'fidelidade', 'figa', 'figado', 'figo', 'figura', 'fila',
  'filamento', 'filantropía', 'filete', 'filha', 'filhote', 'filial', 'filmar', 'filme',
  'filosofia', 'filtrar', 'fim', 'finado', 'final', 'finalizar', 'financiar', 'finar',
  'findar', 'fineza', 'fingir', 'finito', 'fino', 'fio', 'firma', 'firmar',
  'firme', 'fiscal', 'fisgar', 'fisica', 'fisico', 'fissura', 'fita', 'fitar',
  'fixar', 'flacidez', 'flagelo', 'flagrar', 'flama', 'flanco', 'flanela', 'flash',
  'flauta', 'flecha', 'flexao', 'flexionar', 'flexivel', 'floco', 'flora', 'florecer',
  'floresta', 'florir', 'florzinha', 'fluente', 'fluido', 'fluir', 'fluorescente', 'flutuar',
  'fluxo', 'fobia', 'foca', 'focalizar', 'focinho', 'foco', 'fofoca', 'fogao',
  'fogo', 'fogueira', 'foguete', 'foice', 'folclore', 'folego', 'folga', 'folha',
  'folhagem', 'folhear', 'folheto', 'fome', 'fomento', 'fonte', 'fora', 'forca',
  'forcar', 'forjar', 'forma', 'formalizar', 'formar', 'formato', 'formidavel', 'formiga',
  'formoso', 'formula', 'formular', 'fornalha', 'fornecer', 'forno', 'foro', 'forrar',
  'fortalecer', 'forte', 'fortuito', 'fortuna', 'forum', 'fosco', 'fossa', 'fossil',
  'foto', 'fotografar', 'fraco', 'fragata', 'fragil', 'fragmentar', 'fraldas', 'frango',
  'franja', 'franqueza', 'franquia', 'frase', 'fraternidade', 'fraude', 'freira', 'freio',
  'frente', 'frequente', 'fresco', 'frestas', 'fretar', 'friccao', 'frieza', 'frigideira',
  'frio', 'frisar', 'fritura', 'frívolo', 'fronha', 'frota', 'frouxo', 'frugal',
  'frustrar', 'fruta', 'fruteira', 'frutificar', 'fruto', 'fuba', 'fuga', 'fugaz',
  'fugir', 'fulano', 'fumaca', 'fumar', 'funcao', 'funcionar', 'fundar', 'fundo',
  'funebre', 'funeral', 'fungo', 'funil', 'furar', 'furia', 'furioso', 'furo',
  'furtar', 'fusao', 'fuselagem', 'fusivel', 'fuso', 'futebol', 'futuro', 'fuzil',
  'gabar', 'gabinete', 'gado', 'gafieira', 'gago', 'gaiato', 'gaiola', 'gaita',
  'gajo', 'gala', 'galante', 'galaxia', 'galeria', 'galho', 'galinha', 'galo',
  'galope', 'galpao', 'gama', 'gambiarra', 'gana', 'gancho', 'gangue', 'ganhar',
  'ganso', 'garagem', 'garantir', 'garatuja', 'garça', 'garfada', 'garfo', 'gargalhada',
  'garganta', 'garimpo', 'garota', 'garra', 'garrafa', 'garupa', 'gas', 'gasolina',
  'gastar', 'gasto', 'gata', 'gatilho', 'gato', 'gaveta', 'gazeta', 'geada',
  'gêlo', 'gema', 'gemeo', 'gemer', 'gemido', 'gene', 'genero', 'generoso',
  'genese', 'genetica', 'gengibre', 'genial', 'genio', 'genoma', 'gente', 'gentil',
  'genuino', 'geografía', 'geometria', 'geração', 'geral', 'geranio', 'gerar', 'gerencia',
  'gerente', 'germe', 'germinar', 'gestar', 'gestao', 'gesto', 'gigante', 'gilete',
  'gincana', 'ginásio', 'ginasta', 'gingar', 'gira', 'girar', 'girassol', 'giro',
  'glacial', 'gladiador', 'glamour', 'glândula', 'glicerina', 'global', 'globo', 'gloria',
  'glossario', 'glutão', 'glutonaria', 'gnomos', 'goela', 'goleiro', 'golfe', 'golfinho',
  'golpe', 'gomo', 'gongo', 'gordura', 'gorila', 'gorjeta', 'gorro', 'gostar',
  'gosto', 'gota', 'gotejar', 'gotico', 'governar', 'governo', 'gozar', 'graca',
  'gracejo', 'grade', 'graduação', 'grafico', 'gralha', 'grama', 'gramado', 'gramatica',
  'grampo', 'grande', 'grandeza', 'granito', 'granjeiro', 'grão', 'gratuito', 'grau',
  'gravador', 'gravar', 'gravata', 'grave', 'grávida', 'gravura', 'graxa', 'grego',
  'grelha', 'gremio', 'greve', 'grifar', 'grifo', 'grilhão', 'grilo', 'gripe',
  'grisalho', 'gritar', 'grito', 'grosso', 'grua', 'grude', 'grunhir', 'grupo',
  'gruta', 'guarda', 'guardar', 'guarida', 'guarnição', 'guerra', 'guerreiro', 'gueto',
  'guia', 'guiar', 'guilhotina', 'guinada', 'guincho', 'guindaste', 'guisado', 'guitarra',
  'guloso', 'gume', 'guru', 'habitação', 'habitante', 'habitar', 'habito', 'habituar',
  'hálito', 'hamster', 'hangar', 'harmonia', 'harpa', 'haste', 'haxixe', 'hediondo',
  'hegemonia', 'hélice', 'helio', 'hematoma', 'hemisferio', 'hemorragia', 'hepatite', 'herança',
  'herdar', 'herdeiro', 'herege', 'heresia', 'hermetismo', 'hernia', 'heroi', 'hesitar',
  'hibernar', 'hibrido', 'hidratação', 'hidrofobo', 'higiene', 'hilario', 'hino', 'hiperativo',
  'hipico', 'hipnotismo', 'hipocrita', 'hipoteca', 'hipotese', 'histeria', 'historia', 'hoje',
  'holanda', 'holofote', 'holograma', 'homem', 'homeopatia', 'homicidio', 'homenagem', 'homogeneo',
  'honestidade', 'honesto', 'honra', 'honrar', 'hora', 'horda', 'horizonte', 'hormonío',
  'horror', 'horta', 'hospedagem', 'hospedar', 'hospital', 'hostil', 'hotel', 'humano',
  'humilde', 'humor', 'iceberg', 'ícone', 'idade', 'ideal', 'ideia', 'idêntico',
  'identidade', 'identificar', 'ideologia', 'idioma', 'idiota', 'idolatrar', 'ídolo', 'idoso',
  'ignorar', 'igreja', 'igual', 'igualdade', 'iguana', 'ilegal', 'ilegível', 'ilha',
  'ilhota', 'ilícito', 'ilimitado', 'iludir', 'iluminar', 'ilusão', 'ilustrar', 'imagem',
  'imaginar', 'ímã', 'imbecil', 'imediato', 'imensidao', 'imenso', 'imergir', 'imigrar',
  'iminente', 'imitar', 'imobiliario', 'imovel', 'impacto', 'imparcial', 'impasse', 'impávido',
  'imperador', 'imperar', 'imperativo', 'imperdoavel', 'imperial', 'império', 'impermeável', 'ímpeto',
  'implantar', 'implicar', 'implorar', 'impor', 'importar', 'impossível', 'imposto', 'impotência',
  'impressão', 'imprimir', 'improvável', 'improvisar', 'impulso', 'impune', 'impuro', 'imputar',
  'imune', 'imutável', 'inábil', 'inabitável', 'inacabado', 'inadequado', 'inalterado', 'inanição',
  'inaugurar', 'incansável', 'incapaz', 'incendiar', 'incentivar', 'incerto', 'inchar', 'incidência',
  'incidir', 'incluir', 'inclusive', 'incoerente', 'incolor', 'incomodar', 'incomparável', 'incondicional',
  'inconsciência', 'incontável', 'incorporar', 'incorreto', 'incrédulo', 'incrementar', 'incrível', 'incubar',
  'incutir', 'indagar', 'indecisão', 'indeciso', 'indefeso', 'independente', 'indescritível', 'indesejável',
  'indexar', 'indicar', 'índice', 'indiferença', 'indígena', 'indignar', 'índigo', 'indireto',
  'indispor', 'individual', 'indivíduo', 'indolente', 'indolor', 'indulgente', 'indústria', 'induzir',
  'inédito', 'inercia', 'inerte', 'inevitável', 'inexorável', 'infame', 'infância', 'infantaria',
  'infantil', 'infarto', 'infectar', 'infeliz', 'inferior', 'inferno', 'infidelidade', 'infinidade',
  'infinito', 'inflamar', 'inflexível', 'influenciar', 'informar', 'infrator', 'infundir', 'ingênuo',
  'inglês', 'ingrato', 'ingrediente', 'ingressar', 'ingresso', 'inibir', 'iniciar', 'início',
  'inimigo', 'injeção', 'injetar', 'injusto', 'inocente', 'inoculação', 'inodoro', 'inoportuno',
  'inovação', 'inovar', 'inquérito', 'inquietar', 'inquilino', 'insalubre', 'insanidade', 'inscrever',
  'inseguro', 'inserir', 'inseticida', 'inseto', 'insignificante', 'insistir', 'insolar', 'insólito',
  'insone', 'inspecionar', 'inspirar', 'instalar', 'instante', 'instaurar', 'instigar', 'instinto',
  'instituição', 'instruir', 'instrumento', 'insulto', 'insurreição', 'intacto', 'integral', 'integrar',
  'inteiro', 'intelectual', 'inteligência', 'inteligente', 'intempérie', 'intenção', 'intenso', 'intentar',
  'intercâmbio', 'interditar', 'interessar', 'interface', 'interferir', 'interior', 'internar', 'interpretar',
  'interrogar', 'interromper', 'intervalo', 'intervir', 'intestino', 'intimidade', 'intitular', 'intolerante',
  'intoxicar', 'intriga', 'introduzir', 'intruso', 'intuição', 'inundar', 'inútil', 'invadir',
  'invalidar', 'invasão', 'inventar', 'inverno', 'investir', 'invicto', 'invisível', 'invocar',
  'involuntário', 'iodo', 'ioga', 'ir', 'ira', 'iraniano', 'iris', 'irlanda',
  'irmandade', 'irmão', 'ironia', 'irradiar', 'irreal', 'irregular', 'irrigar', 'irritar',
  'irromper', 'isca', 'isenção', 'isento', 'islã', 'isolar', 'isqueiro', 'israelense',
  'isto', 'italiano', 'item', 'itinerário', 'iu', 'já', 'jabuticaba', 'jacaré',
  'jacinto', 'jade', 'jaguar', 'jamais', 'janeiro', 'janela', 'jangada', 'jantar',
  'japonês', 'jarda', 'jardim', 'jardineiro', 'jarro', 'jasmim', 'jato', 'jaula',
  'javali', 'jazigo', 'jazz', 'jeans', 'jeito', 'jejum', 'jiboia', 'joalheria',
  'joelho', 'jogador', 'jogar', 'jogo', 'joia', 'jornal', 'jornalista', 'jornada',
  'jorrar', 'jovem', 'jovial', 'jubileu', 'judaísmo', 'judeu', 'judicial', 'judo',
  'jugo', 'juiz', 'julgamento', 'julgar', 'julho', 'junção', 'junho', 'juntar',
  'júpiter', 'jurado', 'jurar', 'jurídico', 'juros', 'justamente', 'justiça', 'justo',
  'juvenil', 'juventude'
];

// Gera número aleatório criptograficamente seguro
function getSecureRandomIndex(max: number): number {
  const array = new Uint32Array(1);
  crypto.getRandomValues(array);
  return array[0] % max;
}

// 6 palavras × 11 bits cada = 66 bits de entropia
export function generateRecoveryWords(count: number = 6): string[] {
  const words: string[] = [];
  const usedIndices = new Set<number>();
  
  while (words.length < count) {
    const index = getSecureRandomIndex(wordList.length);
    if (!usedIndices.has(index)) {
      usedIndices.add(index);
      words.push(wordList[index]);
    }
  }
  
  return words;
}

export function validateRecoveryWords(input: string[], stored: string[]): boolean {
  if (input.length !== stored.length) return false;
  
  const normalizedInput = input.map(w => w.toLowerCase().trim());
  const normalizedStored = stored.map(w => w.toLowerCase().trim());
  
  return normalizedInput.every((word, index) => word === normalizedStored[index]);
}

// Verifica se uma palavra existe na wordlist
export function isValidWord(word: string): boolean {
  return wordList.includes(word.toLowerCase().trim());
}
